from fpdf import FPDF
from datetime import datetime

class MeetingPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Auralis Meeting Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Auralis AI', 0, 0, 'C')

def generate_meeting_pdf(meeting_data):
    pdf = MeetingPDF()
    pdf.add_page()
    
    # Title & Metadata
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, meeting_data.get('title', 'Untitled Meeting'), 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 7, f"Date: {meeting_data.get('date', 'N/A')}", 0, 1)
    pdf.cell(0, 7, f"Duration: {meeting_data.get('duration', 'N/A')}", 0, 1)
    pdf.cell(0, 7, f"Participants: {meeting_data.get('participants_count', 1)}", 0, 1)
    pdf.ln(5)
    
    # Summary Section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' MEETING SUMMARY', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 10)
    pdf.ln(2)
    pdf.multi_cell(0, 7, meeting_data.get('summary', 'No summary available.'))
    pdf.ln(10)
    
    # Transcript Section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, ' FULL TRANSCRIPT', 0, 1, 'L', True)
    pdf.set_font('Arial', '', 9)
    pdf.ln(2)
    pdf.multi_cell(0, 5, meeting_data.get('transcript', 'No transcript available.'))
    
    return pdf.output(dest='S')
